# Generated by Django 3.2.4 on 2021-09-02 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_is_staff'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.customuser')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'Employees',
                'permissions': [('can_edit_lessons', 'Can edit students lessons '), ('can_edit_info', 'Can edit students info ')],
            },
            bases=('accounts.customuser',),
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Major',
                'verbose_name_plural': 'Majors',
                'db_table': 'Mjaors',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'university',
                'verbose_name_plural': 'University',
                'db_table': 'university',
            },
        ),
        migrations.AlterModelOptions(
            name='classes',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='college',
            options={'verbose_name': 'College', 'verbose_name_plural': 'Colleges'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'permissions': [('can_edit_lessons', 'Can edit students lessons ')], 'verbose_name': 'Professor', 'verbose_name_plural': 'Professors'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.RemoveField(
            model_name='professor',
            name='college_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='books_in_rent',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='unit',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterModelTable(
            name='classes',
            table='Classes',
        ),
        migrations.AlterModelTable(
            name='college',
            table='Colleges',
        ),
        migrations.AlterModelTable(
            name='lesson',
            table='Lessons',
        ),
        migrations.AlterModelTable(
            name='professor',
            table='Professors',
        ),
        migrations.AlterModelTable(
            name='student',
            table='Students',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AddField(
            model_name='major',
            name='college_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.college'),
        ),
        migrations.AddField(
            model_name='employee',
            name='college_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.college'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='major',
            field=models.ForeignKey(default='majer', on_delete=django.db.models.deletion.CASCADE, to='university.major'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='field',
            field=models.ForeignKey(default='IT', on_delete=django.db.models.deletion.CASCADE, to='university.major'),
            preserve_default=False,
        ),
    ]
